"""Fix enum columns to use native_enum=False

Revision ID: 931e6bf7cc20
Revises: 001_initial
Create Date: 2026-02-16 07:39:05.011338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '931e6bf7cc20'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create new enum types (used by alter_column below) so PostgreSQL knows they exist
    new_enums = [
        ("notificationtype", "('PAYMENT_APPROVED', 'PAYMENT_REJECTED', 'PAYMENT_RESUBMIT_REQUESTED', 'ORDER_STATUS_UPDATED', 'ORDER_DISPATCHED', 'ORDER_DELIVERED', 'NEW_ORDER', 'NEW_PAYMENT_SUBMITTED')"),
        ("orderstatus", "('PENDING_PAYMENT', 'PAYMENT_SUBMITTED', 'PAYMENT_RESUBMIT_REQUESTED', 'PAYMENT_REJECTED', 'PAID', 'PACKING', 'DISPATCHED', 'DELIVERED', 'CANCELLED')"),
        ("otptype", "('PHONE', 'EMAIL')"),
        ("otppurpose", "('LOGIN', 'VERIFICATION', 'PASSWORD_RESET')"),
        ("paymentmethodtype", "('BANK_TRANSFER', 'MOBILE_MONEY', 'OTHER')"),
        ("paymentstatus", "('SUBMITTED', 'APPROVED', 'REJECTED', 'RESUBMIT_REQUESTED')"),
        ("userrole", "('CUSTOMER', 'SALES', 'ADMIN')"),
    ]
    for enum_name, enum_values in new_enums:
        op.execute(
            f"DO $$ BEGIN CREATE TYPE {enum_name} AS ENUM {enum_values}; EXCEPTION WHEN duplicate_object THEN null; END $$;"
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_categories_is_active', table_name='categories')
    op.drop_index('idx_categories_parent_id', table_name='categories')
    op.drop_index('idx_categories_slug', table_name='categories')
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_unique_constraint(None, 'categories', ['name'])
    op.drop_index('idx_delivery_zones_is_active', table_name='delivery_zones', postgresql_where='(is_active = true)')
    op.drop_index('idx_delivery_zones_name', table_name='delivery_zones')
    op.create_index(op.f('ix_delivery_zones_is_active'), 'delivery_zones', ['is_active'], unique=False)
    op.create_index(op.f('ix_delivery_zones_name'), 'delivery_zones', ['name'], unique=True)
    op.alter_column('notifications', 'type',
               existing_type=postgresql.ENUM('PAYMENT_APPROVED', 'PAYMENT_REJECTED', 'PAYMENT_RESUBMIT_REQUESTED', 'ORDER_STATUS_UPDATED', 'ORDER_DISPATCHED', 'ORDER_DELIVERED', 'NEW_ORDER', 'NEW_PAYMENT_SUBMITTED', name='notification_type_enum'),
               type_=sa.Enum('PAYMENT_APPROVED', 'PAYMENT_REJECTED', 'PAYMENT_RESUBMIT_REQUESTED', 'ORDER_STATUS_UPDATED', 'ORDER_DISPATCHED', 'ORDER_DELIVERED', 'NEW_ORDER', 'NEW_PAYMENT_SUBMITTED', name='notificationtype'),
               existing_nullable=False)
    op.drop_index('idx_notifications_created_at', table_name='notifications')
    op.drop_index('idx_notifications_is_read', table_name='notifications', postgresql_where='(is_read = false)')
    op.drop_index('idx_notifications_related_order', table_name='notifications')
    op.drop_index('idx_notifications_related_payment', table_name='notifications')
    op.drop_index('idx_notifications_user_id', table_name='notifications')
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_related_order_id'), 'notifications', ['related_order_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_payment_id'), 'notifications', ['related_payment_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_index('idx_order_items_order_id', table_name='order_items')
    op.drop_index('idx_order_items_product_id', table_name='order_items')
    op.drop_index('idx_order_items_variant_id', table_name='order_items')
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_order_items_variant_id'), 'order_items', ['variant_id'], unique=False)
    op.alter_column('order_status_history', 'old_status',
               existing_type=postgresql.ENUM('PENDING_PAYMENT', 'PAYMENT_SUBMITTED', 'PAYMENT_RESUBMIT_REQUESTED', 'PAYMENT_REJECTED', 'PAID', 'PACKING', 'DISPATCHED', 'DELIVERED', 'CANCELLED', name='order_status_enum'),
               type_=sa.Enum('PENDING_PAYMENT', 'PAYMENT_SUBMITTED', 'PAYMENT_RESUBMIT_REQUESTED', 'PAYMENT_REJECTED', 'PAID', 'PACKING', 'DISPATCHED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               existing_nullable=True)
    op.alter_column('order_status_history', 'new_status',
               existing_type=postgresql.ENUM('PENDING_PAYMENT', 'PAYMENT_SUBMITTED', 'PAYMENT_RESUBMIT_REQUESTED', 'PAYMENT_REJECTED', 'PAID', 'PACKING', 'DISPATCHED', 'DELIVERED', 'CANCELLED', name='order_status_enum'),
               type_=sa.Enum('PENDING_PAYMENT', 'PAYMENT_SUBMITTED', 'PAYMENT_RESUBMIT_REQUESTED', 'PAYMENT_REJECTED', 'PAID', 'PACKING', 'DISPATCHED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               existing_nullable=False)
    op.drop_index('idx_order_status_history_created_at', table_name='order_status_history')
    op.drop_index('idx_order_status_history_order_created', table_name='order_status_history')
    op.drop_index('idx_order_status_history_order_id', table_name='order_status_history')
    op.create_index(op.f('ix_order_status_history_created_at'), 'order_status_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('PENDING_PAYMENT', 'PAYMENT_SUBMITTED', 'PAYMENT_RESUBMIT_REQUESTED', 'PAYMENT_REJECTED', 'PAID', 'PACKING', 'DISPATCHED', 'DELIVERED', 'CANCELLED', name='order_status_enum'),
               type_=sa.Enum('PENDING_PAYMENT', 'PAYMENT_SUBMITTED', 'PAYMENT_RESUBMIT_REQUESTED', 'PAYMENT_REJECTED', 'PAID', 'PACKING', 'DISPATCHED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING_PAYMENT'::order_status_enum"))
    op.drop_index('idx_orders_created_at', table_name='orders')
    op.drop_index('idx_orders_delivery_zone_id', table_name='orders')
    op.drop_index('idx_orders_order_number', table_name='orders')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_status_created', table_name='orders')
    op.drop_index('idx_orders_user_id', table_name='orders')
    op.drop_index('idx_orders_user_status', table_name='orders')
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_delivery_zone_id'), 'orders', ['delivery_zone_id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.alter_column('otp_codes', 'type',
               existing_type=postgresql.ENUM('phone', 'email', name='otp_type_enum'),
               type_=sa.Enum('PHONE', 'EMAIL', name='otptype'),
               existing_nullable=False)
    op.alter_column('otp_codes', 'purpose',
               existing_type=postgresql.ENUM('login', 'verification', 'password_reset', name='otp_purpose_enum'),
               type_=sa.Enum('LOGIN', 'VERIFICATION', 'PASSWORD_RESET', name='otppurpose'),
               existing_nullable=False)
    op.drop_index('idx_otp_codes_code', table_name='otp_codes')
    op.drop_index('idx_otp_codes_expires_at', table_name='otp_codes')
    op.drop_index('idx_otp_codes_identifier', table_name='otp_codes')
    op.drop_index('idx_otp_codes_identifier_type', table_name='otp_codes', postgresql_where='(used_at IS NULL)')
    op.create_index(op.f('ix_otp_codes_code'), 'otp_codes', ['code'], unique=False)
    op.create_index(op.f('ix_otp_codes_expires_at'), 'otp_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otp_codes_identifier'), 'otp_codes', ['identifier'], unique=False)
    op.alter_column('payment_methods', 'type',
               existing_type=postgresql.ENUM('BANK_TRANSFER', 'MOBILE_MONEY', 'OTHER', name='payment_method_type_enum'),
               type_=sa.Enum('BANK_TRANSFER', 'MOBILE_MONEY', 'OTHER', name='paymentmethodtype'),
               existing_nullable=False)
    op.drop_index('idx_payment_methods_is_active', table_name='payment_methods', postgresql_where='(is_active = true)')
    op.drop_index('idx_payment_methods_sort_order', table_name='payment_methods', postgresql_where='(is_active = true)')
    op.drop_index('idx_payment_methods_type', table_name='payment_methods')
    op.create_index(op.f('ix_payment_methods_is_active'), 'payment_methods', ['is_active'], unique=False)
    op.create_index(op.f('ix_payment_methods_type'), 'payment_methods', ['type'], unique=False)
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('submitted', 'approved', 'rejected', 'resubmit_requested', name='payment_status_enum'),
               type_=sa.Enum('SUBMITTED', 'APPROVED', 'REJECTED', 'RESUBMIT_REQUESTED', name='paymentstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'submitted'::payment_status_enum"))
    op.drop_index('idx_payments_created_at', table_name='payments')
    op.drop_index('idx_payments_method_id', table_name='payments')
    op.drop_index('idx_payments_order_id', table_name='payments')
    op.drop_index('idx_payments_reviewed_by', table_name='payments')
    op.drop_index('idx_payments_status', table_name='payments')
    op.drop_index('idx_payments_status_created', table_name='payments', postgresql_where="(status = 'submitted'::payment_status_enum)")
    op.drop_index('idx_payments_submitted_by', table_name='payments')
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_method_id'), 'payments', ['method_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_reviewed_by'), 'payments', ['reviewed_by'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_submitted_by_user_id'), 'payments', ['submitted_by_user_id'], unique=False)
    op.drop_index('idx_product_images_product_id', table_name='product_images')
    op.drop_index('idx_product_images_sort_order', table_name='product_images')
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.drop_index('idx_product_variants_is_active', table_name='product_variants', postgresql_where='(is_active = true)')
    op.drop_index('idx_product_variants_product_id', table_name='product_variants')
    op.drop_index('idx_product_variants_sku', table_name='product_variants', postgresql_where='(sku IS NOT NULL)')
    op.drop_constraint('uq_product_variant_label', 'product_variants', type_='unique')
    op.create_index(op.f('ix_product_variants_is_active'), 'product_variants', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=True)
    op.drop_index('idx_products_category_id', table_name='products')
    op.drop_index('idx_products_deleted_at', table_name='products', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_products_slug', table_name='products')
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_deleted_at'), 'products', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.drop_index('idx_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_token', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_user_id', table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('customer', 'sales', 'admin', name='user_role_enum'),
               type_=sa.Enum('CUSTOMER', 'SALES', 'ADMIN', name='userrole'),
               existing_nullable=False,
               existing_server_default=sa.text("'customer'::user_role_enum"))
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_index('idx_users_email', table_name='users', postgresql_where='((email IS NOT NULL) AND (email_verified = true))')
    op.drop_index('idx_users_phone', table_name='users', postgresql_where='((phone IS NOT NULL) AND (phone_verified = true))')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_telegram_user_id', table_name='users', postgresql_where='(telegram_user_id IS NOT NULL)')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('idx_users_telegram_user_id', 'users', ['telegram_user_id'], unique=False, postgresql_where='(telegram_user_id IS NOT NULL)')
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_phone', 'users', ['phone'], unique=False, postgresql_where='((phone IS NOT NULL) AND (phone_verified = true))')
    op.create_index('idx_users_email', 'users', ['email'], unique=False, postgresql_where='((email IS NOT NULL) AND (email_verified = true))')
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('CUSTOMER', 'SALES', 'ADMIN', name='userrole'),
               type_=postgresql.ENUM('customer', 'sales', 'admin', name='user_role_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'customer'::user_role_enum"))
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.create_index('idx_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('idx_refresh_tokens_token', 'refresh_tokens', ['token'], unique=False)
    op.create_index('idx_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_deleted_at'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.create_index('idx_products_slug', 'products', ['slug'], unique=False)
    op.create_index('idx_products_deleted_at', 'products', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_products_category_id', 'products', ['category_id'], unique=False)
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_is_active'), table_name='product_variants')
    op.create_unique_constraint('uq_product_variant_label', 'product_variants', ['product_id', 'label'])
    op.create_index('idx_product_variants_sku', 'product_variants', ['sku'], unique=False, postgresql_where='(sku IS NOT NULL)')
    op.create_index('idx_product_variants_product_id', 'product_variants', ['product_id'], unique=False)
    op.create_index('idx_product_variants_is_active', 'product_variants', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.create_index('idx_product_images_sort_order', 'product_images', ['product_id', 'sort_order'], unique=False)
    op.create_index('idx_product_images_product_id', 'product_images', ['product_id'], unique=False)
    op.drop_index(op.f('ix_payments_submitted_by_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_reviewed_by'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_method_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.create_index('idx_payments_submitted_by', 'payments', ['submitted_by_user_id'], unique=False)
    op.create_index('idx_payments_status_created', 'payments', ['status', 'created_at'], unique=False, postgresql_where="(status = 'submitted'::payment_status_enum)")
    op.create_index('idx_payments_status', 'payments', ['status'], unique=False)
    op.create_index('idx_payments_reviewed_by', 'payments', ['reviewed_by'], unique=False)
    op.create_index('idx_payments_order_id', 'payments', ['order_id'], unique=False)
    op.create_index('idx_payments_method_id', 'payments', ['method_id'], unique=False)
    op.create_index('idx_payments_created_at', 'payments', ['created_at'], unique=False)
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('SUBMITTED', 'APPROVED', 'REJECTED', 'RESUBMIT_REQUESTED', name='paymentstatus'),
               type_=postgresql.ENUM('submitted', 'approved', 'rejected', 'resubmit_requested', name='payment_status_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'submitted'::payment_status_enum"))
    op.drop_index(op.f('ix_payment_methods_type'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_is_active'), table_name='payment_methods')
    op.create_index('idx_payment_methods_type', 'payment_methods', ['type'], unique=False)
    op.create_index('idx_payment_methods_sort_order', 'payment_methods', ['is_active', 'sort_order'], unique=False, postgresql_where='(is_active = true)')
    op.create_index('idx_payment_methods_is_active', 'payment_methods', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('payment_methods', 'type',
               existing_type=sa.Enum('BANK_TRANSFER', 'MOBILE_MONEY', 'OTHER', name='paymentmethodtype'),
               type_=postgresql.ENUM('BANK_TRANSFER', 'MOBILE_MONEY', 'OTHER', name='payment_method_type_enum'),
               existing_nullable=False)
    op.drop_index(op.f('ix_otp_codes_identifier'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_expires_at'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_code'), table_name='otp_codes')
    op.create_index('idx_otp_codes_identifier_type', 'otp_codes', ['identifier', 'type', 'expires_at'], unique=False, postgresql_where='(used_at IS NULL)')
    op.create_index('idx_otp_codes_identifier', 'otp_codes', ['identifier'], unique=False)
    op.create_index('idx_otp_codes_expires_at', 'otp_codes', ['expires_at'], unique=False)
    op.create_index('idx_otp_codes_code', 'otp_codes', ['code'], unique=False)
    op.alter_column('otp_codes', 'purpose',
               existing_type=sa.Enum('LOGIN', 'VERIFICATION', 'PASSWORD_RESET', name='otppurpose'),
               type_=postgresql.ENUM('login', 'verification', 'password_reset', name='otp_purpose_enum'),
               existing_nullable=False)
    op.alter_column('otp_codes', 'type',
               existing_type=sa.Enum('PHONE', 'EMAIL', name='otptype'),
               type_=postgresql.ENUM('phone', 'email', name='otp_type_enum'),
               existing_nullable=False)
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_delivery_zone_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.create_index('idx_orders_user_status', 'orders', ['user_id', 'status'], unique=False)
    op.create_index('idx_orders_user_id', 'orders', ['user_id'], unique=False)
    op.create_index('idx_orders_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_index('idx_orders_order_number', 'orders', ['order_number'], unique=False)
    op.create_index('idx_orders_delivery_zone_id', 'orders', ['delivery_zone_id'], unique=False)
    op.create_index('idx_orders_created_at', 'orders', ['created_at'], unique=False)
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('PENDING_PAYMENT', 'PAYMENT_SUBMITTED', 'PAYMENT_RESUBMIT_REQUESTED', 'PAYMENT_REJECTED', 'PAID', 'PACKING', 'DISPATCHED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               type_=postgresql.ENUM('PENDING_PAYMENT', 'PAYMENT_SUBMITTED', 'PAYMENT_RESUBMIT_REQUESTED', 'PAYMENT_REJECTED', 'PAID', 'PACKING', 'DISPATCHED', 'DELIVERED', 'CANCELLED', name='order_status_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING_PAYMENT'::order_status_enum"))
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.drop_index(op.f('ix_order_status_history_created_at'), table_name='order_status_history')
    op.create_index('idx_order_status_history_order_id', 'order_status_history', ['order_id'], unique=False)
    op.create_index('idx_order_status_history_order_created', 'order_status_history', ['order_id', 'created_at'], unique=False)
    op.create_index('idx_order_status_history_created_at', 'order_status_history', ['created_at'], unique=False)
    op.alter_column('order_status_history', 'new_status',
               existing_type=sa.Enum('PENDING_PAYMENT', 'PAYMENT_SUBMITTED', 'PAYMENT_RESUBMIT_REQUESTED', 'PAYMENT_REJECTED', 'PAID', 'PACKING', 'DISPATCHED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               type_=postgresql.ENUM('PENDING_PAYMENT', 'PAYMENT_SUBMITTED', 'PAYMENT_RESUBMIT_REQUESTED', 'PAYMENT_REJECTED', 'PAID', 'PACKING', 'DISPATCHED', 'DELIVERED', 'CANCELLED', name='order_status_enum'),
               existing_nullable=False)
    op.alter_column('order_status_history', 'old_status',
               existing_type=sa.Enum('PENDING_PAYMENT', 'PAYMENT_SUBMITTED', 'PAYMENT_RESUBMIT_REQUESTED', 'PAYMENT_REJECTED', 'PAID', 'PACKING', 'DISPATCHED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               type_=postgresql.ENUM('PENDING_PAYMENT', 'PAYMENT_SUBMITTED', 'PAYMENT_RESUBMIT_REQUESTED', 'PAYMENT_REJECTED', 'PAID', 'PACKING', 'DISPATCHED', 'DELIVERED', 'CANCELLED', name='order_status_enum'),
               existing_nullable=True)
    op.drop_index(op.f('ix_order_items_variant_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.create_index('idx_order_items_variant_id', 'order_items', ['variant_id'], unique=False)
    op.create_index('idx_order_items_product_id', 'order_items', ['product_id'], unique=False)
    op.create_index('idx_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_payment_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_order_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_notifications_related_payment', 'notifications', ['related_payment_id'], unique=False)
    op.create_index('idx_notifications_related_order', 'notifications', ['related_order_id'], unique=False)
    op.create_index('idx_notifications_is_read', 'notifications', ['user_id', 'is_read'], unique=False, postgresql_where='(is_read = false)')
    op.create_index('idx_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.Enum('PAYMENT_APPROVED', 'PAYMENT_REJECTED', 'PAYMENT_RESUBMIT_REQUESTED', 'ORDER_STATUS_UPDATED', 'ORDER_DISPATCHED', 'ORDER_DELIVERED', 'NEW_ORDER', 'NEW_PAYMENT_SUBMITTED', name='notificationtype'),
               type_=postgresql.ENUM('PAYMENT_APPROVED', 'PAYMENT_REJECTED', 'PAYMENT_RESUBMIT_REQUESTED', 'ORDER_STATUS_UPDATED', 'ORDER_DISPATCHED', 'ORDER_DELIVERED', 'NEW_ORDER', 'NEW_PAYMENT_SUBMITTED', name='notification_type_enum'),
               existing_nullable=False)
    op.drop_index(op.f('ix_delivery_zones_name'), table_name='delivery_zones')
    op.drop_index(op.f('ix_delivery_zones_is_active'), table_name='delivery_zones')
    op.create_index('idx_delivery_zones_name', 'delivery_zones', ['name'], unique=False)
    op.create_index('idx_delivery_zones_is_active', 'delivery_zones', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.create_index('idx_categories_slug', 'categories', ['slug'], unique=False)
    op.create_index('idx_categories_parent_id', 'categories', ['parent_id'], unique=False)
    op.create_index('idx_categories_is_active', 'categories', ['is_active'], unique=False)
    # ### end Alembic commands ###

